### ISSUE TITLE
DB Schema

### ISSUE THREAD

**Issue by danieltigse** [Criptext/Monkey-Chat-Android#35]
@Table(name = "MessageItem")
@Column(index = true)
TEXT senderSessionId
@Column(index = true)
TEXT receiverSessionId
TEXT messageId
TEXT oldMessageId
TEXT messageContent
LONG timestamp
LONG timestampOrder
LONG audioDuration
BOOL isIncoming
INTEGER status
INTEGER itemType
TEXT params
TEXT props

@Table(name = "ConversationItem")
@Column(index = true)
TEXT idConv
TEXT name
LONG dateTime
TEXT secondaryText
INTEGER totalNewMessage
BOOL isGroup
TEXT groupMembers
TEXT avatarFilePath
INTEGER status

**Comment by luisloaiza** [comment]
You have to index all this and put PKs as well. The engine will handle the lookup

**Comment by danieltigse** [comment]
Ok I edit the description. Regarding the PK, the ORM add me one automatically.

```
One important thing to note is that ActiveAndroid creates an id field for your tables. This field is an auto-incrementing primary key.
```

https://github.com/pardom/ActiveAndroid/wiki/Creating-your-database-model
